authors:
- {name: '陈星含'}
- {name: '刘蕴之'}
description: "A collection of notable concepts and equations. Can be used as a textbook. Compiled 2022-05-16"
format: PDF, compiled from LaTeX
name: Lightweight Textbook
